os: linux
dist: trusty

language: node_js
node_js:
  - lts

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng build --config production
  - npm run coveralls
